#! /bin/env bash

# Set PS1 colors

THIS_FILE="$HOME/.bashrc.d/PS1_colors"

#############################
# COLORS

COLORS=(
NONE_COLOR=""

## Base colors
RED_DARK=1
RED=9
GREEN_DARK=2
GREEN=10
BLUE=4
BLUE_LIGHT=12
YELLOW=3
YELLOW_LIGHT=11
PURPLE=5
PURPLE_LIGHT=13
CYAN=6
CYAN_LIGHT=14
GREY_LIGHT=7
GREY_DARK=8
WHITE=15
WHITE_SOFT=254
BLACK=16

## Additional colors
PINK=199
MAGENTA=207
MAGENTA_LIGHT=213
ROSE=205
SALMON=211
TAFFY=212
VIOLET=141
INDIGO=105
LAVENDER=111
AZURE=39
AZURE_LIGHT=45
BLUE_PALE=117
AQUA=123
SCARLET=196
ORANGE=202
AMBER=214
GOLD=220
PISTACHIO=71
JADE=107
TEA=150
ALMOND=173
CHOCO=174
)


# Set color names
for color in ${COLORS[@]};do export $color ;done

COLOR_NAMES=(${COLORS[@]%=*})

get_color_number () { set | grep "^${1^^}=" ;}



#############################
# DEFAULTS
LOCAL_PS1_COLORS_CONFIG="$HOME/.my_ps1_colors"

my_ps1_colors () {
RESET="\[\033[0m\]"
DEFAULT_MIDDLE_DOT="\[\033[38;5;${GREY_DARK}m\]\$·${RESET}"

DEFAULT_LEADING_SPACE=" "
DEFAULT_TRAILING_SPACE=""

DEFAULT_COLOR_1=$PISTACHIO
DEFAULT_COLOR_2=$NONE_COLOR
DEFAULT_COLOR_3=$CYAN
DEFAULT_COLOR_4=$NONE_COLOR
DEFAULT_BOLD=1  ## 1 or empty
}



#############################

display_help () {
    echo -e " \033[4mUsage:\033[0m $ set_colors [COMMAND]
    or: $ set_colors (color_1 | _ ) [color_2 | _] [color_3 | _] [color_4 | _] [classic]
    or: $ <predefined schema name> [classic]

    To set PS1 colors, provide at least one color name or number(0-256).
    _ keeps the value of the parameter.

    Defaults are specified in the 'DEFAULTS' section of the 'PS_colors' file.
    Or in the 'LOCAL_PS1_COLORS_CONFIG' file ($LOCAL_PS1_COLORS_CONFIG).
    The latter takes precedence.


    \033[4mCommands:\033[0m
        reset               reset to defaults
        reset init          reset to initial configuration (alternative: call 'my_ps1_colors')
        list colors [l]     list predefined color names
        list schemas [l]    list predefined color schemas
        save                save prefernces to the local config ($LOCAL_PS1_COLORS_CONFIG)
        help                display this help

    \033[4mExamples:\033[0m
        Select colors
            $ set_colors red
            $ set_colors red classic
            $ set_colors 16 gold black white
            $ set_colors _ _ cyan _
            $ set_colors _ _ cyan _ classic

        Schema
            $ gold
            $ gold classic
            $ tea_b     # black color 1
            $ dir_blue  # path color

        Commands
            $ set_colors reset
            $ set_colors list colors
            $ set_colors list schemas l
    "
}


list_colors () {
    if [[ $1 ]]; then
        echo ${COLOR_NAMES[@],} | tr '[:lower:][:upper:]' '[:upper:][:lower:]' | tr ' ' '\n'
    else
        echo ${COLOR_NAMES[@],} | tr '[:lower:][:upper:]' '[:upper:][:lower:]'
    fi
}


list_schemas () {
    SCHEMA_NAMES=(${schemas[@]%% *})
    if [[ $1 ]]; then
        echo ${SCHEMA_NAMES[@],,} | tr ' ' '\n'
    else
        echo ${SCHEMA_NAMES[@],,}
    fi
}


validate_color_name () {
    for color in ${COLOR_NAMES[@],,}; do
        [[ $color = ${1,,} ]] && return
    done
    echo -e "\033[01;31m[Error]\033[0m Unknown color name: $1 \n Available colors: "
    list_colors
    return 1
}


validate_color_number () {
    if [[ $1 -gt 256 ]]; then
        echo -e "\033[01;31m[Error]\033[0m Wrong parameter. The color number must be in the range 0-256"
        return 1
    fi
}


set_PS1_colors_classic () {
    ## STYLE_1 - the first part of PS1 (user@host)
    ##   COLOR_1 - text color, COLOR_2 - background color
    ## STYLE_2 - the second part of PS1 (path)
    ##   COLOR_3 - text color, COLOR_4 - background color
    STYLE_1="\[\033[38;5;${COLOR_1};48;5;${COLOR_2}m\]"
    STYLE_2="\[\033[38;5;${COLOR_3};48;5;${COLOR_4}m\]"

    PS1="\n${STYLE_1}${LEADING_SPACE}\u@\h${TRAILING_SPACE}${RESET}:${STYLE_2}\w${RESET} \n${MIDDLE_DOT}"
}


set_PS1_colors () {
    ## STYLE_1 - the first part of PS1 (user@host)
    ##   COLOR_1 - background color, COLOR_2 - text color
    ## STYLE_2 - the second part of PS1 (path)
    ##   COLOR_3 - background color, COLOR_4 - text color
    ## BOLD=1
    STYLE_1="\[\033[${BOLD};38;5;${COLOR_2};48;5;${COLOR_1}m\]"
    STYLE_2="\[\033[${BOLD};38;5;${COLOR_4};48;5;${COLOR_3}m\]"

    LEADING_SYMBOL="\[\033[38;5;${COLOR_1};48;5;${NONE_COLOR}m\]"    ## \uE0B6
    DELIMITER="\[\033[38;5;${COLOR_1};48;5;${COLOR_3}m\]"            ## \uE0BC
    ENDING_SYMBOL="\[\033[38;5;${COLOR_3};48;5;${NONE_COLOR}m\]"     ## \uE0B0

    PS1="\n${LEADING_SYMBOL}${RESET}${STYLE_1}\u@\h${DELIMITER}${RESET}${STYLE_2}\w${RESET}${ENDING_SYMBOL}${RESET}\n${MIDDLE_DOT}"
}


save_PS1_colors () {
    echo "RESET=\"$RESET\""                            > $LOCAL_PS1_COLORS_CONFIG
    echo "MIDDLE_DOT=\"$MIDDLE_DOT\""                  >> $LOCAL_PS1_COLORS_CONFIG
    echo "DEFAULT_LEADING_SPACE=\"$LEADING_SPACE\""    >> $LOCAL_PS1_COLORS_CONFIG
    echo "DEFAULT_TRAILING_SPACE=\"$TRAILING_SPACE\""  >> $LOCAL_PS1_COLORS_CONFIG
    echo "DEFAULT_COLOR_1=$COLOR_1"                    >> $LOCAL_PS1_COLORS_CONFIG
    echo "DEFAULT_COLOR_2=$COLOR_2"                    >> $LOCAL_PS1_COLORS_CONFIG
    echo "DEFAULT_COLOR_3=$COLOR_3"                    >> $LOCAL_PS1_COLORS_CONFIG
    echo "DEFAULT_COLOR_4=$COLOR_4"                    >> $LOCAL_PS1_COLORS_CONFIG
    echo "DEFAULT_BOLD=$BOLD"                          >> $LOCAL_PS1_COLORS_CONFIG
    echo -e "\033[01;32mSaved to $LOCAL_PS1_COLORS_CONFIG \033[m \n"
    cat $LOCAL_PS1_COLORS_CONFIG
}


set_colors () {
    # Print help
    [[ -z $1 || $1 =~ "help" ]] && display_help && return

    # Reset to defaults
    if [[ $1 = "reset" ]]; then
        my_ps1_colors
        [[ -f $LOCAL_PS1_COLORS_CONFIG && $2 != "init" ]] && source $LOCAL_PS1_COLORS_CONFIG
        COLOR_1=$DEFAULT_COLOR_1 ; COLOR_2=$DEFAULT_COLOR_2  ## STYLE_1
        COLOR_3=$DEFAULT_COLOR_3 ; COLOR_4=$DEFAULT_COLOR_4  ## STYLE_2
        LEADING_SPACE=$DEFAULT_LEADING_SPACE; TRAILING_SPACE=$DEFAULT_TRAILING_SPACE
        MIDDLE_DOT=$DEFAULT_MIDDLE_DOT
        BOLD=$DEFAULT_BOLD
        set_PS1_colors
        return
    fi

    # List predefined color names/ schemas
    if [[ $1 = "list" ]]; then
        if [[ $2 = "colors" ]]; then
            list_colors $3
            return
        elif [[ $2 = "schemas" ]]; then
            list_schemas $3
            return
        else
            echo -e "\033[01;31m[Error]\033[0m Wrong option for the 'list' command ($2). Available options: \n\tcolors \n\tschemas"
            return 1
        fi
    fi

    # Save preferences
    if [[ $1 = "save" ]]; then
        save_PS1_colors
        return
    fi

    ### Text color 1
    C1=${1^^}
    if [[ $C1 =~ ^[0-9]+$ ]]; then
        validate_color_number $C1 || return 1
        COLOR_1=$C1
    elif [[ $C1 = "_" ]] || [[ $C1 = "CLASSIC" ]]; then
        true
    else
        validate_color_name $C1 || return 1
        COLOR_1=${!C1}  ## Resolve C1 text value to the color number
    fi

    ### Background color 1
    if [[ -n $2 ]]; then
        C2=${2^^}
        if [[ $C2 =~ ^[0-9]{1,3}$ ]]; then
            validate_color_number $C2 || return 1
            COLOR_2=$C2
            LEADING_SPACE=" "; TRAILING_SPACE=" "
            if [[ $C2 = 256 ]]; then TRAILING_SPACE=$DEFAULT_TRAILING_SPACE ;fi
        elif [[ $C2 = "_" ]] || [[ $C2 = "CLASSIC" ]]; then
            true
        else
            validate_color_name $C2 || return 1
            COLOR_2=${!C2}
            LEADING_SPACE=" "; TRAILING_SPACE=" "
            if [[ $C2 = "NONE_COLOR" ]]; then TRAILING_SPACE=$DEFAULT_TRAILING_SPACE ;fi
        fi
    else
        COLOR_2=$DEFAULT_COLOR_2
        LEADING_SPACE=$DEFAULT_LEADING_SPACE; TRAILING_SPACE=$DEFAULT_TRAILING_SPACE
    fi

    ### Text color 2
    if [[ -n $3 ]]; then
        C3=${3^^}
        if [[ $C3 =~ ^[0-9]{1,3}$ ]]; then
            validate_color_number $C3 || return 1
            COLOR_3=$C3
        elif [[ $C3 = "_" ]] || [[ $C3 = "CLASSIC" ]]; then
            true
        else
            validate_color_name $C3 || return 1
            COLOR_3=${!C3}
        fi
    else
        COLOR_3=$DEFAULT_COLOR_3
    fi

    # Background color 2
    if [[ -n $4 ]]; then
        C4=${4^^}
        if [[ $C4 =~ ^[0-9]{1,3}$ ]]; then
            validate_color_number $C4 || return 1
            COLOR_4=$C4
        elif [[ $C4 = "_" ]] || [[ $C4 = "CLASSIC" ]]; then
            true
        else
            validate_color_name $C4 || return 1
            COLOR_4=${!C4}
        fi
    else
        COLOR_4=$DEFAULT_COLOR_4
    fi

    LAST_ARGUMENT="${@: -1}"
    if [[ ${LAST_ARGUMENT^^} = "CLASSIC" ]]; then
        set_PS1_colors_classic
    else
        set_PS1_colors
    fi
}


set_colors reset




#############################
# PREDEFINED SCHEMAS

schemas=(
# Text
"red () { set_colors RED NONE_COLOR CHOCO NONE_COLOR \$1 ;}"
"gold () { set_colors GOLD NONE_COLOR TEA NONE_COLOR \$1 ;}"
"orange () { set_colors ORANGE NONE_COLOR _ _ \$1 ;}"
"amber () { set_colors AMBER NONE_COLOR _ _ \$1 ;}"
"yellow () { set_colors YELLOW_LIGHT NONE_COLOR _ _ \$1 ;}"
"green () { set_colors GREEN NONE_COLOR _ _ \$1 ;}"
"pista () { set_colors PISTACHIO NONE_COLOR CHOCO NONE_COLOR \$1 ;}"
"jade () { set_colors JADE NONE_COLOR ALMOND NONE_COLOR \$1 ;}"
"tea () { set_colors TEA NONE_COLOR _ _ \$1 ;}"
"azure () { set_colors AZURE_LIGHT NONE_COLOR _ _ \$1 ;}"
"blue () { set_colors BLUE_PALE NONE_COLOR CHOCO NONE_COLOR \$1 ;}"
"aqua () { set_colors AQUA NONE_COLOR _ _ \$1 ;}"
"choco () { set_colors CHOCO NONE_COLOR _ _ \$1 ;}"
"almond () { set_colors ALMOND NONE_COLOR BLUE_PALE NONE_COLOR \$1 ;}"
"lavender () { set_colors LAVENDER NONE_COLOR _ _ \$1 ;}"
"indigo () { set_colors INDIGO NONE_COLOR _ _ \$1 ;}"
"violet () { set_colors VIOLET NONE_COLOR _ _ \$1 ;}"
"pink () { set_colors PINK NONE_COLOR _ _ \$1 ;}"
"taffy () { set_colors TAFFY NONE_COLOR _ _ \$1 ;}"
"magenta () { set_colors MAGENTA NONE_COLOR _ _ \$1 ;}"
"rose () { set_colors ROSE NONE_COLOR _ _ \$1 ;}"
"salmon () { set_colors SALMON NONE_COLOR _ _ \$1 ;}"

# Backgrounds
"red_b () { set_colors WHITE RED _ _ \$1 ;}"
"orange_b () { set_colors BLACK ORANGE _ _ \$1 ;}"
"orange_w () { set_colors WHITE ORANGE _ _ \$1 ;}"
"gold_b () { set_colors BLACK GOLD _ _ \$1 ;}"
"amber_b () { set_colors BLACK AMBER _ _ \$1 ;}"
"yellow_b () { set_colors BLACK YELLOW_LIGHT _ _ \$1 ;}"
"green_b () { set_colors BLACK PISTACHIO _ _ \$1 ;}"
"jade_b () { set_colors BLACK JADE _ _ \$1 ;}"
"tea_b () { set_colors BLACK TEA _ _ \$1 ;}"
"choco_w () { set_colors 253 CHOCO _ _ \$1 ;}"
"choco_b () { set_colors BLACK CHOCO _ _ \$1 ;}"
"almond_w () { set_colors 253 ALMOND _ _ \$1 ;}"
"almond_b () { set_colors BLACK ALMOND _ _ \$1 ;}"
"violet_b () { set_colors BLACK VIOLET _ _ \$1 ;}"
"violet_w () { set_colors 254 99 _ _ \$1 ;}"
"indigo_b () { set_colors BLACK INDIGO _ _ \$1 ;}"
"lavender_b () { set_colors BLACK LAVENDER _ _ \$1 ;}"
"azure_b () { set_colors BLACK AZURE_LIGHT _ _ \$1 ;}"
"cyan_w () { set_colors 255 CYAN _ _ \$1 ;}"
"blue_b () { set_colors BLACK BLUE_PALE _ _ \$1 ;}"
"aqua_b () { set_colors BLACK AQUA _ _ \$1 ;}"
"purple_w () { set_colors 254 PURPLE _ _ \$1 ;}"
"taffy_b () { set_colors BLACK TAFFY _ _ \$1 ;}"
"pink_b () { set_colors BLACK PINK _ _ \$1 ;}"
"pink_w () { set_colors 255 PINK _ _ \$1 ;}"
"magenta_b () { set_colors BLACK MAGENTA_LIGHT _ _ _ \$1 ;}"
"rose_b () { set_colors BLACK ROSE _ _ \$1 ;}"
"rose_w () { set_colors 255 ROSE _ _ \$1 ;}"
"salmon_b () { set_colors BLACK SALMON _ _ \$1 ;}"

# Path
"dir_choco () { set_colors _ _ CHOCO NONE_COLOR \$1 ;}"
"dir_almond () { set_colors _ _ ALMOND NONE_COLOR \$1 ;}"
"dir_salmon () { set_colors _ _ SALMON NONE_COLOR \$1 ;}"
"dir_violet () { set_colors _ _ VIOLET NONE_COLOR \$1 ;}"
"dir_indigo () { set_colors _ _ INDIGO NONE_COLOR \$1 ;}"
"dir_lavender () { set_colors _ _ LAVENDER NONE_COLOR \$1 ;}"
"dir_blue () { set_colors _ _ BLUE_PALE NONE_COLOR \$1 ;}"
"dir_aqua () { set_colors _ _ AQUA NONE_COLOR \$1 ;}"
"dir_gold () { set_colors _ _ GOLD NONE_COLOR \$1 ;}"
"dir_yellow () { set_colors _ _ YELLOW_LIGHT NONE_COLOR \$1 ;}"
"dir_pista () { set_colors _ _ PISTACHIO NONE_COLOR \$1 ;}"
"dir_jade () { set_colors _ _ JADE NONE_COLOR \$1 ;}"
"dir_tea () { set_colors _ _ TEA NONE_COLOR \$1 ;}"
)


# Set schemas
for schema in "${schemas[@]}"; do eval $schema ;done




#############################
# LS_COLORS

display_help_ls_colors () {
    echo -e " \033[4mUsage:\033[0m $ set_ls_colors [COMMAND]
    or: $ set_ls_colors file_type text_color [background_color | _]

    To update LS_COLORS, provide file type and at least one color name or number(0-256).
    _ keeps the value of the parameter.

    To check predefined file types, use:
        $ dircolors -p


    \033[4mCommands:\033[0m
        reset           reset to saved user defaults ($LOCAL_LS_COLORS_CONFIG)
        reset init      reset to initial user configuration (alternative: call 'my_ls_colors')
        reset system    reset to system defaults
        list [l]        list predefined color names
        save            save prefernces to the local config ($LOCAL_LS_COLORS_CONFIG)
        help            display this help

    \033[4mExamples:\033[0m
        Set colors
            $ set_ls_colors ln cyan
            $ set_ls_colors di 16 yellow_light
            $ set_ls_colors di tea _

        Commands
            $ set_ls_colors reset
            $ set_ls_colors list l
    "
}


escape_symbols () {
    echo $1 | sed 's/\*/\\*/g; s/\./\\./g'
}


save_ls_colors () {
    echo "LS_COLORS=\"$LS_COLORS\"" > $LOCAL_LS_COLORS_CONFIG
    echo -e "\033[01;32mSaved to $LOCAL_LS_COLORS_CONFIG \033[0m"
    cat $LOCAL_LS_COLORS_CONFIG
}


set_ls_colors () {
    # Print help
    [[ -z $1 || $1 =~ "help" ]] && display_help_ls_colors && return

    # Reset to defaults
    if [[ $1 = "reset" ]]; then
        if [[ $2 = "system" ]]; then
            export LS_COLORS="$(dircolors -c | cut -d' ' -f3 | tr -d "'" )"
            echo -e "\033[01;32mReset to system defaults. \033[0m"
            echo "LS_COLOR=$LS_COLORS"
        elif [[ $2 = "init" ]]; then
            echo -e "\033[01;32mReset to initial user configuration.\033[m"
            my_ls_colors
        else
            if [[ -f $LOCAL_LS_COLORS_CONFIG ]]; then
                source $LOCAL_LS_COLORS_CONFIG
                echo -e "\033[01;32mReset to user default preferences.\033[m (Config: $LOCAL_LS_COLORS_CONFIG)"
                echo "LS_COLOR=$LS_COLORS"
            else
                echo -e "\033[01;32m$LOCAL_LS_COLORS_CONFIG file not found."
                echo -e "Reset to initial user configuration.\033[m"
                my_ls_colors
            fi
        fi

        return
    fi

    # List predefined color names
    if [[ $1 = "list" ]]; then
        list_colors $2
        return
    fi

    # Save preferences
    if [[ $1 = "save" ]]; then
        save_ls_colors
        return
    fi

    # File type
    if [[ -n $1 ]]; then
        TYPE="${1,,}"
        TYPE_ESC="$(escape_symbols $TYPE)"
    else
        echo -e "\033[01;31m[Error]\033[0m Missing parameter. Provide file type."
        return 1
    fi

    # Text color
    if [[ -n $2 ]]; then
        if [[ $2 =~ ^[0-9]{1,3}$ ]]; then
            validate_color_number $2 || return 1
            TEXT_COLOR=$2
        else
            validate_color_name $2 || return 1
            C2=${2^^} && TEXT_COLOR=${!C2}
        fi
    else
        echo -e "\033[01;31m[Error]\033[0m Missing parameter. Provide the color name or number(0-255)"
        return 1
    fi

    # Background color
    if [[ -n $3 ]]; then
        if [[ $3 =~ ^[0-9]{1,3}$ ]]; then
            validate_color_number $3 || return 1
            BACKGROUND=$3
        elif [[ $3 = "_" ]]; then
            true
        else
            validate_color_name $3 || return 1
            C3=${3^^} && BACKGROUND=${!C3}
        fi
    else
        BACKGROUND=$NONE_COLOR
    fi


    LS_COLORS="$(echo $LS_COLORS | sed -E 's/'$TYPE_ESC'=(.{1,3};){1,5}.{1,3}://g')$TYPE=38;5;$TEXT_COLOR;48;5;$BACKGROUND:"
}




#############################
# LS_COLORS preferences

LOCAL_LS_COLORS_CONFIG="$HOME/.my_ls_colors"

my_ls_colors () {
    set_ls_colors di AZURE      # Directories
    set_ls_colors ln AQUA       # Links

    #yaml
    set_ls_colors '*.yaml' blue_pale
    set_ls_colors '*.yml' blue_pale

    echo "LS_COLOR=$LS_COLORS"
}


set_ls_colors reset >/dev/null
